In [2]:
import numpy as np
np.random.seed(123)

expected_action_value =  np.random.uniform(0 ,1 , 10)
print(expected_action_value)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]


In [26]:
num_epoch = 1000
estimated = np.zeros(10) + 9.5
pulled    = np.zeros(10)

for iter in range(num_epoch):
    
    if np.random.uniform(0,1) > 0.2:
        random_choice = np.argmax(estimated)
    else:
        random_choice = np.argmax(np.random.uniform(0,1,10))
        
    pulled[random_choice] = pulled[random_choice] + 1
    
    if np.random.uniform(0,1) > expected_action_value[random_choice]:
        reward[random_choice] = (reward[random_choice] + 1)
        


In [27]:
print(np.around(expected_action_value,3))
print(np.around(reward,3))
print(np.around(pulled,3))
print(np.around(reward/pulled,3))

[0.696 0.286 0.227 0.551 0.719 0.423 0.981 0.685 0.481 0.392]
[306.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
[1000.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
[0.306   nan   nan   nan   nan   nan   nan   nan   nan   nan]


C:\ProgramData\Miniconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.
