In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [99]:
import numpy as np
np.random.seed(123)

expected_action_value  = np.random.uniform(0 ,1 , 10)
num_epoch = 1000
alpha = 0.006
beta  = 0.002
print(expected_action_value)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]


In [150]:
# Linear Reward Inaction 
estimated = np.zeros(10)+0.5
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated) if np.random.uniform(0,1)>0.2 else: np.random.choice
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    mask = np.zeros(10) 
    mask[current_choice] = 1

    if current_reward == 1:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
    else:
        estimated = (mask) * ((1-beta)*estimated) + (1-mask) * (beta/9.0 + (1-beta)*estimated)

    print(current_reward)
    print(estimated)
    input()
        
print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))

1
[0.503 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497]

1
[0.505982 0.494018 0.494018 0.494018 0.494018 0.494018 0.494018 0.494018
 0.494018 0.494018]

1
[0.50894611 0.49105389 0.49105389 0.49105389 0.49105389 0.49105389
 0.49105389 0.49105389 0.49105389 0.49105389]

0
[0.50792822 0.49029401 0.49029401 0.49029401 0.49029401 0.49029401
 0.49029401 0.49029401 0.49029401 0.49029401]

0
[0.50691236 0.48953564 0.48953564 0.48953564 0.48953564 0.48953564
 0.48953564 0.48953564 0.48953564 0.48953564]

1
[0.50987089 0.48659843 0.48659843 0.48659843 0.48659843 0.48659843
 0.48659843 0.48659843 0.48659843 0.48659843]

0
[0.50885114 0.48584745 0.48584745 0.48584745 0.48584745 0.48584745
 0.48584745 0.48584745 0.48584745 0.48584745]

1
[0.51179804 0.48293237 0.48293237 0.48293237 0.48293237 0.48293237
 0.48293237 0.48293237 0.48293237 0.48293237]

1
[0.51472725 0.48003477 0.48003477 0.48003477 0.48003477 0.48003477
 0.48003477 0.48003477 0.48003477 0.48003477]

0
[0.51369779 0.47929693 0.


1
[0.62765132 0.34804414 0.34804414 0.34804414 0.34804414 0.34804414
 0.34804414 0.34804414 0.34804414 0.34804414]



KeyboardInterrupt: 

In [148]:
# Linear Reward Inaction 
estimated = np.zeros(10)+0.5
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated)
    
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    print(estimated)
    if current_reward == 1:
        mask = np.zeros(10) 
        mask[current_choice] = 1
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
    print(current_reward)
    print(estimated)
    input()
        
print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))

[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
1
[0.503 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497]

[0.503 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497]
0
[0.503 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497]

[0.503 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497]
1
[0.505982 0.494018 0.494018 0.494018 0.494018 0.494018 0.494018 0.494018
 0.494018 0.494018]

[0.505982 0.494018 0.494018 0.494018 0.494018 0.494018 0.494018 0.494018
 0.494018 0.494018]
1
[0.50894611 0.49105389 0.49105389 0.49105389 0.49105389 0.49105389
 0.49105389 0.49105389 0.49105389 0.49105389]

[0.50894611 0.49105389 0.49105389 0.49105389 0.49105389 0.49105389
 0.49105389 0.49105389 0.49105389 0.49105389]
1
[0.51189243 0.48810757 0.48810757 0.48810757 0.48810757 0.48810757
 0.48810757 0.48810757 0.48810757 0.48810757]



KeyboardInterrupt: 