In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [28]:
import numpy as np
np.random.seed(123)

expected_action_value  = np.random.uniform(0 ,1 , 10)
num_epoch = 1000
alpha = 0.3
beta  = 1.0 - alpha
print(expected_action_value)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]


In [85]:
# linear reward
estimated = np.zeros(10)
pull_count= np.zeros(10)

for iter in range(num_epoch):
    current_choice = np.argmax(estimated)
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    if current_reward == 1:
        mask = np.ones(10) 
        mask[current_choice] = 0
        estimated[current_choice] = estimated[current_choice] + alpha * (1-estimated[current_choice])
        estimated = ((1-alpha) * estimated) * mask + (1-mask) * estimated
    else:
        mask = np.ones(10) 
        mask[current_choice] = 0
        estimated[current_choice] = (1-beta) * estimated[current_choice]  
        estimated = (beta/9.0 + (1-beta) * estimated) * mask+ (1-mask) * estimated
        
print(np.around(expected_action_value,3))
print(np.around(estimated,3))

[0.696 0.286 0.227 0.551 0.719 0.423 0.981 0.685 0.481 0.392]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


In [74]:
temp = np.ones(10)
temp[3] = 0
print(temp)

[1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
