In [48]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(123)

expected_action_value  = np.random.uniform(0 ,1 , 10)
expected_action_value = expected_action_value/expected_action_value.sum()
num_epoch = 10000
alpha = 0.2
beta  = 0.8
print(expected_action_value)

[0.12798052 0.05257987 0.04168536 0.1013075  0.13220688 0.07774843
 0.18022149 0.1258417  0.08837421 0.07205402]


In [49]:
# Linear Reward Inaction 
estimated = np.zeros(10)+0.1
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated) if np.random.uniform(0,1) > 0.3 else np.random.choice(10, p=estimated)
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    mask = np.zeros(10) 
    mask[current_choice] = 1

    if current_reward == 1:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
    else:
        estimated = (mask) * ((1-beta)*estimated) + (1-mask) * (beta/9.0 + (1-beta)*estimated)

print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))
print(estimated.sum())

[0.128 0.053 0.042 0.101 0.132 0.078 0.18  0.126 0.088 0.072]
[0.111 0.11  0.111 0.111 0.095 0.107 0.111 0.111 0.111 0.022]
[1026.  961.  947.  994. 1030.  978. 1092. 1026.  971.  975.]
0.9999999999999999


In [52]:
# Linear Reward Inaction 
alpha = 0.00001
estimated = np.zeros(10)+0.1
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated) if np.random.uniform(0,1) > 0.9 else np.random.choice(10, p=estimated)
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    mask = np.zeros(10) 
    mask[current_choice] = 1
    
    if current_reward == 1:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
        
    estimated = estimated/estimated.sum()
        
print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))
print(estimated.sum())

[0.128 0.053 0.042 0.101 0.132 0.078 0.18  0.126 0.088 0.072]
[0.1   0.1   0.099 0.1   0.1   0.1   0.102 0.1   0.1   0.1  ]
[ 879.  949.  914.  970.  953.  916. 1732.  933.  879.  875.]
1.0


In [68]:
import random, datetime, numpy as np, math
random.seed(datetime.datetime.now())

def lrI(alpha):
	print("\n\nStarting LRI - Linear Reward Inaction Algorithm\n\n")
	for j in range(1):
		levers = ["q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9", "q10"]
		reward_percent = [random.random() for i in range(10)]
		lever_count, reward_count  = ([0 for i in range(10)] for i in range(2))
		#probability of choosing a lever - sum equal to 1
		lever_probability = [0.1 for i in range(10)]
		optimal_decision = 0
		#randomly choose a lever and set alpha/beta values
		lever = random.randint(0, 9)
		beta = 0
		#gets lever that is the most optimal (has the highest chance of giving us a reward)
		optimal_decision = reward_percent.index(max(reward_percent))
		i = 1
		while i <= 10000:
		# if reward = 1
			if random.random() < reward_percent[lever]:
				reward_count[lever]+=1
				#update the current lever
				lever_probability[lever] = lever_probability[lever] + alpha * (1- lever_probability[lever])
				#update other levers
				for x in range(0, len(lever_probability)):
					if x is not lever:
						lever_probability[x] = (1 - alpha) * lever_probability[x]
			lever_count[lever] += 1
			i+=1
			#choose the lever according to the probability distribution lever_probability
			lever = np.random.choice(10, p=lever_probability)

		print("Run: %d, Optimal Decision: %s with chance: %f chosen %d times. Average reward: %.2f" % (j+1, levers[optimal_decision], reward_percent[optimal_decision], lever_count[optimal_decision], sum(reward_count)/i))
		print(np.around(reward_percent,3))
		print(np.around(lever_probability,3))
		print(lever_count)
        
def lrI2(alpha):
    print("\n\nStarting LRI - Linear Reward Inaction Algorithm\n\n")
    for j in range(1):
        levers = ["q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9", "q10"]
        reward_percent = [random.random() for i in range(10)]
        lever_count, reward_count  = ([0 for i in range(10)] for i in range(2))
        lever_probability = np.zeros(10) + 0.1
        optimal_decision = 0
        lever = random.randint(0, 9)
        optimal_decision = reward_percent.index(max(reward_percent))
        i = 1
        while i <= 10000:
            if random.random() < reward_percent[lever]:
                reward_count[lever] = reward_count[lever] + 1
                mask = np.zeros(10)
                mask[lever] = mask[lever] + 1
                lever_probability = (mask) * (lever_probability + alpha*(1-lever_probability)) + (1-mask) *((1 - alpha) * lever_probability)

            lever_count[lever] += 1; i+=1
            lever = np.random.choice(10, p=lever_probability)

        print("Run: %d, Optimal Decision: %s with chance: %f chosen %d times / 10000"% 
              (j+1, levers[optimal_decision], reward_percent[optimal_decision], lever_count[optimal_decision])  )
        print(np.around(reward_percent,3))
        print(np.around(lever_probability,3))
        print(lever_count)
        
alpha2 =  0.01
lrI(alpha2)
lrI2(alpha2)



Starting LRI - Linear Reward Inaction Algorithm


Run: 1, Optimal Decision: q8 with chance: 0.829062 chosen 9164 times. Average reward: 0.82
[0.581 0.787 0.709 0.379 0.54  0.607 0.287 0.829 0.78  0.105]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[109, 96, 193, 63, 79, 88, 26, 9164, 156, 26]


Starting LRI - Linear Reward Inaction Algorithm


Run: 1, Optimal Decision: q7 with chance: 0.931256 chosen 9595 times / 10000
[0.724 0.43  0.344 0.877 0.466 0.545 0.931 0.351 0.096 0.249]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[139, 43, 18, 66, 40, 43, 9595, 17, 17, 22]


# Reference 
1. Michael Pacheco. (2019). Michaelpacheco.net. Retrieved 9 January 2019, from https://www.michaelpacheco.net/blog/RL-multi-armed-bandit-2
2. numpy.random.choice — NumPy v1.15 Manual. (2019). Docs.scipy.org. Retrieved 9 January 2019, from https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.choice.html

In [37]:
lever_probability = np.random.uniform(0,1,10)
lever_probability = lever_probability/lever_probability.sum()
print(np.random.choice(10, p=lever_probability))


0
7
