In [48]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(123)

expected_action_value  = np.random.uniform(0 ,1 , 10)
expected_action_value = expected_action_value/expected_action_value.sum()
num_epoch = 10000
alpha = 0.2
beta  = 0.8
print(expected_action_value)

[0.12798052 0.05257987 0.04168536 0.1013075  0.13220688 0.07774843
 0.18022149 0.1258417  0.08837421 0.07205402]


In [49]:
# Linear Reward Inaction 
estimated = np.zeros(10)+0.1
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated) if np.random.uniform(0,1) > 0.3 else np.random.choice(10, p=estimated)
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    mask = np.zeros(10) 
    mask[current_choice] = 1

    if current_reward == 1:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
    else:
        estimated = (mask) * ((1-beta)*estimated) + (1-mask) * (beta/9.0 + (1-beta)*estimated)

print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))
print(estimated.sum())

[0.128 0.053 0.042 0.101 0.132 0.078 0.18  0.126 0.088 0.072]
[0.111 0.11  0.111 0.111 0.095 0.107 0.111 0.111 0.111 0.022]
[1026.  961.  947.  994. 1030.  978. 1092. 1026.  971.  975.]
0.9999999999999999


In [52]:
# Linear Reward Inaction 
alpha = 0.00001
estimated = np.zeros(10)+0.1
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated) if np.random.uniform(0,1) > 0.9 else np.random.choice(10, p=estimated)
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    mask = np.zeros(10) 
    mask[current_choice] = 1
    
    if current_reward == 1:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
        
    estimated = estimated/estimated.sum()
        
print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))
print(estimated.sum())

[0.128 0.053 0.042 0.101 0.132 0.078 0.18  0.126 0.088 0.072]
[0.1   0.1   0.099 0.1   0.1   0.1   0.102 0.1   0.1   0.1  ]
[ 879.  949.  914.  970.  953.  916. 1732.  933.  879.  875.]
1.0
