In [8]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(123)

expected_action_value  = np.random.uniform(0 ,1 , 10)
expected_action_value = expected_action_value/expected_action_value.sum()
num_epoch = 10000
alpha = 0.006
beta  = 0.002
print(expected_action_value)

[0.12798052 0.05257987 0.04168536 0.1013075  0.13220688 0.07774843
 0.18022149 0.1258417  0.08837421 0.07205402]


In [28]:
# Linear Reward Inaction 
estimated = np.zeros(10)+0.1
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated) if np.random.uniform(0,1) > 0.3 else np.random.choice(10, p=estimated)
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    mask = np.zeros(10) 
    mask[current_choice] = 1

    if current_reward == 1:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
    else:
        estimated = (mask) * ((1-beta)*estimated) + (1-mask) * (beta/9.0 + (1-beta)*estimated)

print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))

[0.128 0.053 0.042 0.101 0.132 0.078 0.18  0.126 0.088 0.072]
[0.282 0.074 0.077 0.079 0.083 0.077 0.088 0.08  0.079 0.082]
[7725.  229.  235.  262.  262.  260.  275.  255.  246.  251.]


In [31]:
# Linear Reward Inaction 
estimated = np.zeros(10)+0.1
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated) if np.random.uniform(0,1) > 0.5 else np.random.choice(10, p=estimated)
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    mask = np.zeros(10) 
    mask[current_choice] = 1
    
    if current_reward == 1:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
        
    estimated = estimated/estimated.sum()
        
print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))

[0.128 0.053 0.042 0.101 0.132 0.078 0.18  0.126 0.088 0.072]
[0.973 0.001 0.    0.005 0.001 0.    0.02  0.    0.    0.   ]
[8844.   83.   95.  190.  109.   87.  260.  108.  115.  109.]
