In [8]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(123)

expected_action_value  = np.random.uniform(0 ,1 , 10)
expected_action_value = expected_action_value/expected_action_value.sum()
num_epoch = 10000
alpha = 0.006
beta  = 0.002
print(expected_action_value)

[0.12798052 0.05257987 0.04168536 0.1013075  0.13220688 0.07774843
 0.18022149 0.1258417  0.08837421 0.07205402]


In [12]:
# Linear Reward Inaction 
estimated = np.zeros(10)+0.5
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated) if np.random.uniform(0,1) > 0.3 else np.random.choice(range(10))
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    mask = np.zeros(10) 
    mask[current_choice] = 1

    if current_reward == 1:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
    else:
        estimated = (mask) * ((1-beta)*estimated) + (1-mask) * (beta/9.0 + (1-beta)*estimated)

print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))

[0.128 0.053 0.042 0.101 0.132 0.078 0.18  0.126 0.088 0.072]
[0.075 0.075 0.071 0.082 0.082 0.078 0.311 0.075 0.07  0.08 ]
[ 294.  334.  314.  288.  311. 1212. 6326.  315.  317.  289.]


In [14]:
# Linear Reward Inaction 
estimated = np.zeros(10)+0.5
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated)
    
    current_choice = np.argmax(estimated) if np.random.uniform(0,1) > 0.3 else np.random.choice(range(10))
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    mask = np.zeros(10) 
    mask[current_choice] = 1
    
    if current_reward == 1:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
        
print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))

[0.128 0.053 0.042 0.101 0.132 0.078 0.18  0.126 0.088 0.072]
[0.047 0.005 0.007 0.024 0.017 0.016 0.831 0.018 0.027 0.008]
[ 350.  288.  314.  289.  314.  290. 7280.  295.  281.  299.]
