In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [99]:
import numpy as np
np.random.seed(123)

expected_action_value  = np.random.uniform(0 ,1 , 10)
num_epoch = 1000
alpha = 0.006
beta  = 0.002
print(expected_action_value)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]


In [106]:
# Linear Reward Inaction 
estimated = np.zeros(10)+0.5
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated)
    
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    mask = np.zeros(10) 
    mask[current_choice] = 1

    if current_reward == 1:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
    else:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)

    print(current_reward)
    print(estimated)
    input()
        
print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))

[0.696 0.286 0.227 0.551 0.719 0.423 0.981 0.685 0.481 0.392]
[0.852 0.016 0.016 0.016 0.016 0.016 0.016 0.016 0.016 0.016]


In [148]:
# Linear Reward Inaction 
estimated = np.zeros(10)+0.5
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated)
    
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    print(estimated)
    if current_reward == 1:
        mask = np.zeros(10) 
        mask[current_choice] = 1
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
    print(current_reward)
    print(estimated)
    input()
        
print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))

[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
1
[0.503 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497]

[0.503 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497]
0
[0.503 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497]

[0.503 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497 0.497]
1
[0.505982 0.494018 0.494018 0.494018 0.494018 0.494018 0.494018 0.494018
 0.494018 0.494018]

[0.505982 0.494018 0.494018 0.494018 0.494018 0.494018 0.494018 0.494018
 0.494018 0.494018]
1
[0.50894611 0.49105389 0.49105389 0.49105389 0.49105389 0.49105389
 0.49105389 0.49105389 0.49105389 0.49105389]

[0.50894611 0.49105389 0.49105389 0.49105389 0.49105389 0.49105389
 0.49105389 0.49105389 0.49105389 0.49105389]
1
[0.51189243 0.48810757 0.48810757 0.48810757 0.48810757 0.48810757
 0.48810757 0.48810757 0.48810757 0.48810757]



KeyboardInterrupt: 