In [1]:
import tensorflow as tf
import numpy as np

In [4]:
temp_list = np.array(range(10))
sess  = tf.InteractiveSession()
diagg = tf.matrix_diag(temp_list)
print(temp_list)
print(diagg.eval())

[0 1 2 3 4 5 6 7 8 9]
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


In [ ]:
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt

In [7]:
temp,label = make_blobs(n_features=2)
print(temp.shape)

(100, 2)


In [2]:
! git all-go

[master bd9820c9] s
 2 files changed, 12 insertions(+)
 create mode 100644 NeuralNetwork/principal_component_analysis_regularization/random_notes/.ipynb_checkpoints/notes-checkpoint.ipynb
 create mode 100644 NeuralNetwork/principal_component_analysis_regularization/random_notes/notes.ipynb


The file will have its original line endings in your working directory.
The file will have its original line endings in your working directory.
To https://github.com/JaeDukSeo/Daily-Neural-Network-Practice-2
   f877c05a..bd9820c9  master -> master
