In [1]:
# import Library and some random image data set
import tensorflow as tf
import numpy      as np
import seaborn    as sns 
import pandas     as pd
import os,sys
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
np.random.seed(78); tf.set_random_seed(78)

# get some of the STL data set
from sklearn.preprocessing import OneHotEncoder
from sklearn.utils import shuffle
from skimage import util 
from skimage.transform import resize
from scipy.misc import imresize
from skimage.io import imread
import warnings
from numpy import inf

from scipy.stats import kurtosis,skew

plt.rcParams.update({'font.size': 10})
import warnings
warnings.filterwarnings("ignore")
import gc
from IPython.display import display, clear_output
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d
from matplotlib import animation
%load_ext jupyternotify

from scipy.stats import chi2_contingency
from sklearn.metrics import mutual_info_score
from skimage.filters import roberts, sobel, scharr, prewitt
from skimage import feature
from scipy import stats
# Def: Read STL 10 images
def read_STL10_data():
    # read all of the data (STL 10) https://github.com/mttk/STL10
    def read_all_images(path_to_data):
        """
        :param path_to_data: the file containing the binary images from the STL-10 dataset
        :return: an array containing all the images
        """

        with open(path_to_data, 'rb') as f:
            # read whole file in uint8 chunks
            everything = np.fromfile(f, dtype=np.uint8)

            # We force the data into 3x96x96 chunks, since the
            # images are stored in "column-major order", meaning
            # that "the first 96*96 values are the red channel,
            # the next 96*96 are green, and the last are blue."
            # The -1 is since the size of the pictures depends
            # on the input file, and this way numpy determines
            # the size on its own.

            images = np.reshape(everything, (-1, 3, 96, 96))

            # Now transpose the images into a standard image format
            # readable by, for example, matplotlib.imshow
            # You might want to comment this line or reverse the shuffle
            # if you will use a learning algorithm like CNN, since they like
            # their channels separated.
            images = np.transpose(images, (0, 3, 2, 1))
            return images
    def read_labels(path_to_labels):
        """
        :param path_to_labels: path to the binary file containing labels from the STL-10 dataset
        :return: an array containing the labels
        """
        with open(path_to_labels, 'rb') as f:
            labels = np.fromfile(f, dtype=np.uint8)
            return labels
    def show_images(data,row=1,col=1):
        fig=plt.figure(figsize=(10,10))
        columns = col; rows = row
        for i in range(1, columns*rows +1):
            fig.add_subplot(rows, columns, i)
            plt.imshow(data[i-1])
        plt.show()

    train_images = read_all_images("../../../../DataSet/STL10/stl10_binary/train_X.bin") / 255.0
    train_labels = read_labels    ("../../../../DataSet/STL10/stl10_binary/train_Y.bin")
    test_images  = read_all_images("../../../../DataSet/STL10/stl10_binary/test_X.bin")  / 255.0
    test_labels  = read_labels    ("../../../../DataSet/STL10/stl10_binary/test_y.bin")

    label_encoder= OneHotEncoder(sparse=False,categories='auto')
    train_labels = label_encoder.fit_transform(train_labels.reshape((-1,1)))
    test_labels  = label_encoder.fit_transform(test_labels.reshape((-1,1)))

    print(train_images.shape,train_images.max(),train_images.min())
    print(train_labels.shape,train_labels.max(),train_labels.min())
    print(test_images.shape,test_images.max(),test_images.min())
    print(test_labels.shape,test_labels.max(),test_labels.min())
    return train_images,train_labels,test_images,test_labels
# Def: Read CIFAR 10 images
def read_CIFAR10_data():
    # ====== miscellaneous =====
    # code from: https://github.com/tensorflow/tensorflow/issues/8246
    def tf_repeat(tensor, repeats):
        """
        Args:

        input: A Tensor. 1-D or higher.
        repeats: A list. Number of repeat for each dimension, length must be the same as the number of dimensions in input

        Returns:

        A Tensor. Has the same type as input. Has the shape of tensor.shape * repeats
        """
        expanded_tensor = tf.expand_dims(tensor, -1)
        multiples = [1] + repeats
        tiled_tensor = tf.tile(expanded_tensor, multiples = multiples)
        repeated_tesnor = tf.reshape(tiled_tensor, tf.shape(tensor) * repeats)
        return repeated_tesnor
    def unpickle(file):
        import pickle
        with open(file, 'rb') as fo:
            dict = pickle.load(fo, encoding='bytes')
        return dict
    # ====== miscellaneous =====

    # data
    PathDicom = "../../Dataset/cifar-10-batches-py/"
    lstFilesDCM = []  # create an empty list
    for dirName, subdirList, fileList in os.walk(PathDicom):
        for filename in fileList:
            if not ".html" in filename.lower() and not  ".meta" in filename.lower():  # check whether the file's DICOM
                lstFilesDCM.append(os.path.join(dirName,filename))

    # Read the data traind and Test
    batch0 = unpickle(lstFilesDCM[0])
    batch1 = unpickle(lstFilesDCM[1])
    batch2 = unpickle(lstFilesDCM[2])
    batch3 = unpickle(lstFilesDCM[3])
    batch4 = unpickle(lstFilesDCM[4])

    onehot_encoder = OneHotEncoder(sparse=True)
    train_batch = np.vstack((batch0[b'data'],batch1[b'data'],batch2[b'data'],batch3[b'data'],batch4[b'data']))
    train_label = np.expand_dims(np.hstack((batch0[b'labels'],batch1[b'labels'],batch2[b'labels'],batch3[b'labels'],batch4[b'labels'])).T,axis=1).astype(np.float64)
    train_label = onehot_encoder.fit_transform(train_label).toarray().astype(np.float64)

    test_batch = unpickle(lstFilesDCM[5])[b'data']
    test_label = np.expand_dims(np.array(unpickle(lstFilesDCM[5])[b'labels']),axis=0).T.astype(np.float64)
    test_label = onehot_encoder.fit_transform(test_label).toarray().astype(np.float64)

    # reshape data
    train_batch = np.reshape(train_batch,(len(train_batch),3,32,32)); test_batch = np.reshape(test_batch,(len(test_batch),3,32,32))
    # rotate data
    train_batch = np.rot90(np.rot90(train_batch,1,axes=(1,3)),3,axes=(1,2)).astype(np.float64); test_batch = np.rot90(np.rot90(test_batch,1,axes=(1,3)),3,axes=(1,2)).astype(np.float64)
    # normalize
    train_batch= train_batch/255.0; test_batch = test_batch/255.0

    # print out the data shape and the max and min value
    print(train_batch.shape,train_batch.max(),train_batch.min())
    print(train_label.shape,train_label.max(),train_label.min())
    print(test_batch.shape,test_batch.max(),test_batch.min())
    print(test_label.shape,test_label.max(),test_label.min())
    return train_batch,train_label,test_batch,test_label

<IPython.core.display.Javascript object>

In [51]:
# create the layers
def tf_softmax(x):    return tf.nn.softmax(x)
def tf_elu(x):       return tf.nn.elu(x)
def tf_relu(x):       return tf.nn.relu(x)
def tf_iden(x):       return x
def tf_sigmoid(x):    return tf.nn.sigmoid(x)
def tf_tanh(x):    return tf.nn.tanh(x)
def tf_atan(x): return tf.atan(x)
def tf_softplus(x):   return tf.nn.softplus(x)

class CNN():

    def __init__(self,k,inc,out, stddev=0.05,act=tf_elu):
        self.w              = tf.Variable(tf.random_normal([k,k,inc,out],stddev=stddev,seed=2,dtype=tf.float32))
        self.act = act

    def getw(self): return self.w
    
    # Feed Forward for two variables
    def feedforward(self,input,stride=1,padding='VALID'):
        self.input1  = input
        self.layer1  = tf.nn.conv2d(self.input1,self.w,strides=[1,stride,stride,1],padding=padding) 
        self.layerA1 = self.act(self.layer1)
        return self.layer1, self.layerA1
    def feedforward2(self,input,stride=1,padding='VALID'):
        self.input2  = input
        self.layer2  = tf.nn.conv2d(self.input2,self.w,strides=[1,stride,stride,1],padding=padding) 
        self.layerA2 = self.act(self.layer2)
        return self.layer2, self.layerA2
class tf_instance_norm_layer():
    
    def __init__(self,batch_size,vector_shape):
        self.moving_mean = tf.Variable(tf.zeros(shape=[batch_size,1,1,vector_shape],dtype=tf.float64))
        self.moving_vari = tf.Variable(tf.zeros(shape=[batch_size,1,1,vector_shape],dtype=tf.float64))
        self.axis        = (1,2)
        
    def feedforward(self,input,training_phase=True,eps = 1e-8):
        self.input = input
        self.input_size          = self.input.shape
        self.batch,self.h,self.w,self.c = self.input_size[0].value,self.input_size[1].value,self.input_size[2].value,self.input_size[3].value

        # Training Moving Average Mean         
        def training_fn():
            self.mean    = tf.reduce_mean(self.input,axis=self.axis ,keepdims=True)
            self.var     = tf.reduce_mean(tf.square(self.input-self.mean),axis=self.axis,keepdims=True)
            centered_data= (self.input - self.mean)/tf.sqrt(self.var + eps)
            
            update_variable = []
            update_variable.append(tf.assign(self.moving_mean,self.moving_mean*0.9 + 0.1 * self.mean ))
            update_variable.append(tf.assign(self.moving_vari,self.moving_vari*0.9 + 0.1 * self.var  ))
            return centered_data,update_variable
        
        # Testing Moving Average Mean        
        def  testing_fn():
            centered_data   = (self.input - self.moving_mean)/tf.sqrt(self.moving_vari + eps)
            update_variable = []
            update_variable.append(tf.assign(self.moving_mean,self.moving_mean))
            update_variable.append(tf.assign(self.moving_vari,self.moving_vari))
            return centered_data,update_variable
        
        self.output,update_variable = tf.cond(training_phase,true_fn=training_fn,false_fn=testing_fn)
        return self.output,update_variable
def calc_MI(x, y, bins=(90*90)/4):
    c_xy = np.histogram2d(x, y, bins)[0]
    mi = mutual_info_score(None, None, contingency=c_xy)
    return mi
def softmax_multi(target, axis=(1,2), name=None):
    max_axis   = tf.reduce_max(target, axis, keepdims=True)
    target_exp = tf.exp(target-max_axis)
    normalize  = tf.reduce_sum(target_exp, axis, keepdims=True)
    softmax    = target_exp / normalize
    return softmax

In [12]:
# read the data
train_images,train_labels,test_images,test_labels = read_STL10_data()
train_images = train_images.mean(3,keepdims=True)
train_images = (train_images-train_images.min((0,1,2),keepdims=True))/(train_images.max((0,1,2),keepdims=True)-train_images.min((0,1,2),keepdims=True)+1e-8)
# 1. sym padding 
# 2. sug metn sim -> not a good idea (sparse filtering - population sparsity -)
# 3. sales pitch - data aug (latent space) (paper - how is different from x)
# 4. baseline - other approaches - 
# 5. show negative images 
# 6. sparse filtering
# 7. classifier - mmke it a dense

(5000, 96, 96, 3) 1.0 0.0
(5000, 10) 1.0 0.0
(8000, 96, 96, 3) 1.0 0.0
(8000, 10) 1.0 0.0


In [13]:
# hyeper
num_eps   = 1; num_epoch = 10; learning_rate = 0.0001; batch_size = 20;  alpha = 0.5
beta1,beta2,adam_e  = 0.9,0.999,1e-8; 

In [161]:
# create layers
num_of_aug  = 6
l1_encoder  = CNN(3,1,num_of_aug,           act=tf_elu)
l2_encoder  = CNN(1,  num_of_aug,num_of_aug,act=tf_elu)
l3_encoder  = CNN(3,  num_of_aug,num_of_aug,act=tf_elu)
l4_encoder  = CNN(1,  num_of_aug,num_of_aug,act=tf_elu)
l5_encoder  = CNN(3,  num_of_aug,num_of_aug,act=tf_elu)
l6_encoder  = CNN(1,  num_of_aug,num_of_aug,act=tf_sigmoid)

l1_with_image = CNN(3,num_of_aug*2,num_of_aug*2,act=tf_elu)
l2_with_image = CNN(3,num_of_aug*2,num_of_aug*2,act=tf_elu)
l3_with_image = CNN(3,num_of_aug*2,1,act=tf_iden)

def with_image(input_data):
    _,layer1_g = l1_with_image.feedforward(input_data)
    _,layer2_g = l1_with_image.feedforward(layer1_g)
    _,layer3_g = l1_with_image.feedforward(layer2_g)
    return layer3_g
def with_noise(inpud_data):
    _,l1_noise = l1_with_noise.feedforward(inpud_data)
    _,l2_noise = l2_with_noise.feedforward(l1_noise)
    _,l3_noise = l3_with_noise.feedforward(l2_noise)
    return l3_noise

x_encoding = tf.placeholder(tf.float32,(None,96,96,1))
x_reisze   = tf.image.resize_images(x_encoding,(90,90))
x_reisze   = tf.tile(x_reisze,(1,1,1,num_of_aug))
angle = tf.placeholder(tf.float32,())

_,layer1_e = l1_encoder.feedforward(x_encoding)
_,layer2_e = l2_encoder.feedforward(layer1_e)
_,layer3_e = l3_encoder.feedforward(layer2_e)
_,layer4_e = l4_encoder.feedforward(layer3_e)
_,layer5_e = l5_encoder.feedforward(layer4_e)
_,layer6_e = l6_encoder.feedforward(layer5_e)

final_latent  = layer6_e
# final_latents = tf.transpose(final_latent,(0,2,1,3))
final_latents = tf.contrib.image.rotate(final_latent,angle)
encoded_gt = tf.concat([final_latent  ,x_reisze],3)
encoded_rd = tf.concat([final_latents ,x_reisze],3)

with_image_gt  = tf.reduce_mean(-tf_atan(-with_image(encoded_gt)))
with_image_rd  = tf.reduce_mean( tf_atan( with_image(encoded_rd)))
WITH_IMAGE     = (with_image_rd - with_image_gt) 

# reg = tf.reduce_sum(tf.abs(l1_encoder.getw())) +\
# tf.reduce_sum(tf.abs(l2_encoder.getw())) +\
# tf.reduce_sum(tf.abs(l3_encoder.getw())) +\
# tf.reduce_sum(tf.abs(l4_encoder.getw())) +\
# tf.reduce_sum(tf.abs(l5_encoder.getw())) +\
# tf.reduce_sum(tf.abs(l6_encoder.getw())) 
reg = tf.sqrt(final_latent**2 + 1e-8)
reg = reg/(tf.sqrt(tf.reduce_sum(reg,(1,2),keepdims=True))+1e-8)
# reg = reg/(tf.sqrt(tf.reduce_sum(reg,(1,2),keepdims=True))+1e-8)
reg = tf.reduce_sum(reg)

LOSS = WITH_IMAGE + reg * 0.00001
auto_train = tf.train.AdamOptimizer(0.0008).minimize(LOSS)

In [56]:
# creat classification network
x = tf.placeholder(tf.float32,(None,90,90,1))
y = tf.placeholder(tf.float32,(None,10))
is_training = tf.placeholder_with_default(True,())

l1 = CNN(3,1,32); l2 = CNN(3,32,32); l3 = CNN(3,32,32)
l4 = CNN(3,32,64);l5 = CNN(3,64,64); l6 = CNN(3,64,64)
l7 = CNN(3,64,64);l8 = CNN(1,64,64); l9 = CNN(1,64,10)

_,layer1 = l1.feedforward(x)
layer1 = tf.layers.batch_normalization(layer1, training=is_training)
_,layer2 = l2.feedforward(layer1)
_,layer3 = l3.feedforward(layer2)
layer3   = tf.nn.avg_pool(layer3,ksize=[1,2,2,1],strides=[1,2,2,1],padding='VALID')

_,layer4 = l4.feedforward(layer3)
layer4 = tf.layers.batch_normalization(layer4, training=is_training)
_,layer5 = l5.feedforward(layer4)
_,layer6 = l6.feedforward(layer5)
layer6   = tf.nn.avg_pool(layer6,ksize=[1,2,2,1],strides=[1,2,2,1],padding='VALID')

_,layer7 = l7.feedforward(layer6)
layer7 = tf.layers.batch_normalization(layer7, training=is_training)
_,layer8 = l8.feedforward(layer7)
_,layer9 = l9.feedforward(layer8)

final_layer = tf.reduce_mean(layer9,(1,2))
final_soft  = tf_softmax(final_layer)
cost               = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=final_layer,labels=y))
correct_prediction = tf.equal(tf.argmax(final_soft, 1), tf.argmax(y, 1))
accuracy  = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

extra_update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
class_train = tf.train.AdamOptimizer(learning_rate=0.0008).minimize(cost)

In [162]:
# train the network 
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
num_epoch = 10
angle_list = [30,60,90,120,150,180,210,240,270,300,330]
for iter in range(num_epoch):
    for current_batch_index in range(0,len(train_images),batch_size):
        current_batch = train_images[current_batch_index:current_batch_index+batch_size]
        sess_results  = sess.run([LOSS,auto_train],feed_dict={x_encoding:current_batch,angle:angle_list[iter]})
        sys.stdout.write(' Current Iter : ' + str(iter) + '/'+ str(num_epoch)  + ' batch : ' + str(current_batch_index) + '/'+ str(len(train_images)) + ' loss : ' + str(sess_results[0]) + '\r')
        sys.stdout.flush();    
    if iter%5==0: 
        print('\n')
        train_images = shuffle(train_images)

 Current Iter : 0/10 batch : 4980/5000 loss : -0.25435953474

 Current Iter : 5/10 batch : 4980/5000 loss : -0.76215193



KeyboardInterrupt: 

In [164]:
# show images
capture_best = []
for current_batch_index in range(0,len(train_images),batch_size):
    current_batch = train_images[current_batch_index:current_batch_index+batch_size]
    
    current_image_resize = np.asarray([resize(np.squeeze(x),(90,90)) for x in current_batch])[:,:,:,None]
    #current_image_resize = (current_image_resize-current_image_resize.min((0,1,2),keepdims=True))/(current_image_resize.max((0,1,2),keepdims=True)-current_image_resize.min((0,1,2),keepdims=True)+1e-8)
    latent_feature = sess.run(latent_feature,feed_dict={x_encoding:current_batch})
    #latent_feature = (latent_feature-latent_feature.min((0,1,2),keepdims=True))/(latent_feature.max((0,1,2),keepdims=True)-latent_feature.min((0,1,2),keepdims=True)+1e-8)

    for image_index in range(len(current_batch)-10):
        plt.figure(figsize=(3*num_of_aug+1,6))
        
        plt.subplot(2,num_of_aug+1,1)
        plt.imshow(np.squeeze(current_image_resize[image_index]),cmap='gray')
        upper_bound = calc_MI(current_image_resize[image_index].ravel(),current_image_resize[image_index].ravel())
        plt.title(str(np.around(upper_bound,2)))
        plt.axis('off')
        
        all_image_mi = []
        for image_index2 in range(len(latent_feature.T)): 
            all_image_mi.append(calc_MI(latent_feature[image_index,:,:,image_index2].ravel(),current_image_resize[image_index].ravel()))
        all_image_mi_sort = sorted(range(len(all_image_mi)), key=lambda k: all_image_mi[k])[::-1]
        best_indexn = all_image_mi_sort[0]
        print(all_image_mi_sort)
        print(best_indexn)
        capture_best.append(best_indexn)
        
        count = 2
        for high_index in all_image_mi_sort:
            plt.subplot(2,num_of_aug+1,count)
            plt.imshow(np.squeeze(latent_feature[image_index,:,:,high_index]),cmap='gist_rainbow'); plt.axis('off')
            current_mi= calc_MI(latent_feature[image_index,:,:,high_index].ravel(),current_image_resize[image_index].ravel())
            percent   = 1-(upper_bound-current_mi)/upper_bound
            plt.title(str(np.around(percent,2)))
            count = count + 1
            
        count = count + 1
        for high_index in all_image_mi_sort:
            plt.subplot(2,num_of_aug+1,count)
            plt.imshow(np.squeeze(latent_feature[image_index,:,:,high_index]),cmap='gray'); plt.axis('off')
            current_mi= calc_MI(latent_feature[image_index,:,:,high_index].ravel(),current_image_resize[image_index].ravel())
            percent   = current_mi/upper_bound
            plt.title(str(np.around(percent,2)))
            count = count + 1
            
        plt.show()
    capture_best_index = stats.mode(capture_best)[0]
    print('Best : ',capture_best_index)
    break

TypeError: Fetch argument array([[[[ 1.76597623e-05, -3.71764589e-04, -1.05508592e-03,
           1.69237566e-04,  7.37068651e-04,  8.58296603e-02],
         [ 1.81960368e-05, -3.72373732e-04, -1.05859200e-03,
           1.71897904e-04,  7.38123024e-04,  8.61666799e-02],
         [ 1.89531602e-05, -3.72922135e-04, -1.06168527e-03,
           1.74194880e-04,  7.39217910e-04,  8.64139274e-02],
         ...,
         [ 3.06840084e-05, -3.92937625e-04, -1.16210105e-03,
           2.49323115e-04,  7.69853068e-04,  9.61597264e-02],
         [ 3.06351030e-05, -3.92997637e-04, -1.16204540e-03,
           2.49249861e-04,  7.69847073e-04,  9.61400196e-02],
         [ 3.02905046e-05, -3.92802467e-04, -1.16072677e-03,
           2.48257245e-04,  7.69383914e-04,  9.60994810e-02]],

        [[ 1.20775437e-03, -2.33841259e-02,  1.25744015e-01,
           9.81130600e-02, -1.71036250e-03,  1.55747188e-02],
         [ 1.21134357e-03, -2.35147662e-02,  1.26311317e-01,
           9.85593274e-02, -1.71677617e-03,  1.56644192e-02],
         [ 1.21436676e-03, -2.36115474e-02,  1.26731664e-01,
           9.88905653e-02, -1.72222604e-03,  1.57309454e-02],
         ...,
         [ 1.30301458e-03, -2.69796588e-02,  1.41326964e-01,
           1.10369027e-01, -1.88738771e-03,  1.80567037e-02],
         [ 1.30292319e-03, -2.69749220e-02,  1.41304940e-01,
           1.10351689e-01, -1.88761286e-03,  1.80541314e-02],
         [ 1.30172225e-03, -2.69629154e-02,  1.41252846e-01,
           1.10309742e-01, -1.88521342e-03,  1.80458371e-02]],

        [[-3.13768105e-04, -2.28195917e-04, -1.00876356e-03,
          -1.09003318e-04,  1.14406832e-01,  3.53182033e-02],
         [-3.13590193e-04, -2.26811288e-04, -1.01163995e-03,
          -1.07579406e-04,  1.14950694e-01,  3.55069488e-02],
         [-3.13602271e-04, -2.25317970e-04, -1.01408246e-03,
          -1.06219260e-04,  1.15379415e-01,  3.56553607e-02],
         ...,
         [-3.13956814e-04, -1.86245074e-04, -1.08679838e-03,
          -6.89691733e-05,  1.29650295e-01,  4.06014100e-02],
         [-3.13923141e-04, -1.86738922e-04, -1.08652690e-03,
          -6.93193506e-05,  1.29632190e-01,  4.05952968e-02],
         [-3.14083241e-04, -1.87334706e-04, -1.08571257e-03,
          -6.98115909e-05,  1.29588842e-01,  4.05803472e-02]],

        ...,

        [[-1.99295670e-01, -2.53494978e-02, -2.24228177e-04,
          -1.34606808e-01,  1.28487691e-01,  8.47532137e-05],
         [-1.99964285e-01, -2.54411902e-02, -2.25378331e-04,
          -1.35068044e-01,  1.28927827e-01,  8.29735000e-05],
         [-2.00431451e-01, -2.55049895e-02, -2.27169046e-04,
          -1.35388970e-01,  1.29234716e-01,  8.11130230e-05],
         ...,
         [-2.10006773e-01, -2.67984383e-02, -2.44063078e-04,
          -1.41979337e-01,  1.35527119e-01,  6.03317421e-05],
         [-2.10295185e-01, -2.68375650e-02, -2.43952905e-04,
          -1.42178848e-01,  1.35717139e-01,  6.03465633e-05],
         [-2.10597500e-01, -2.68790778e-02, -2.43981587e-04,
          -1.42388090e-01,  1.35916352e-01,  6.01111715e-05]],

        [[-2.38275528e-02,  4.29840555e-04, -1.28024831e-01,
           1.80572532e-02,  2.79432982e-02, -2.49405310e-01],
         [-2.39209644e-02,  4.31467924e-04, -1.28539860e-01,
           1.81169454e-02,  2.80659739e-02, -2.50379354e-01],
         [-2.39856467e-02,  4.32817382e-04, -1.28903523e-01,
           1.81607138e-02,  2.81527005e-02, -2.51067609e-01],
         ...,
         [-2.52633393e-02,  4.46930440e-04, -1.35906145e-01,
           1.89584065e-02,  2.98187453e-02, -2.64309436e-01],
         [-2.52852421e-02,  4.46911581e-04, -1.36028156e-01,
           1.89725552e-02,  2.98478138e-02, -2.64540374e-01],
         [-2.53124051e-02,  4.47818515e-04, -1.36183321e-01,
           1.89921148e-02,  2.98850592e-02, -2.64834404e-01]],

        [[-1.58404484e-01,  2.87401192e-02, -1.09281182e-01,
           3.65105830e-02,  1.44356827e-03,  4.27679661e-05],
         [-1.59059390e-01,  2.88679954e-02, -1.09744124e-01,
           3.66793014e-02,  1.44586235e-03,  4.33533169e-05],
         [-1.59584492e-01,  2.89705545e-02, -1.10116109e-01,
           3.68135646e-02,  1.44844945e-03,  4.31318404e-05],
         ...,
         [-1.59974411e-01,  2.90741213e-02, -1.10394530e-01,
           3.68701518e-02,  1.48244796e-03,  4.44009784e-05],
         [-1.61268145e-01,  2.93222964e-02, -1.11309014e-01,
           3.72110717e-02,  1.48105074e-03,  4.51098313e-05],
         [-1.62558079e-01,  2.95705087e-02, -1.12220861e-01,
           3.75487357e-02,  1.48127205e-03,  4.57416827e-05]]],


       [[[ 1.01036089e-03,  3.40835121e-03, -6.45923501e-05,
           8.73057730e-03, -1.18657760e-03, -3.95964179e-03],
         [ 9.84058715e-04,  5.50424494e-03, -3.62131868e-05,
           2.83335578e-02, -5.28812548e-03, -1.48023758e-02],
         [ 9.25650995e-04,  8.03370588e-03, -3.23852546e-05,
           5.31076714e-02, -1.04698678e-02, -2.86014602e-02],
         ...,
         [ 8.67383205e-04,  1.55862207e-02, -2.58270811e-05,
           1.23139843e-01, -2.51886006e-02, -6.73346370e-02],
         [ 8.00539332e-04,  1.24228084e-02, -6.66566048e-05,
           9.48490053e-02, -1.93344969e-02, -5.17059714e-02],
         [ 7.50035804e-04,  1.08444048e-02, -9.27880756e-05,
           8.12101960e-02, -1.65130626e-02, -4.42058109e-02]],

        [[-6.99836412e-04, -2.15192139e-03,  5.45096642e-04,
          -3.86711932e-03, -3.39143735e-05, -1.23029307e-03],
         [-6.81456353e-04,  1.60635589e-03,  5.28528937e-04,
          -1.49883190e-02,  6.35532103e-03, -1.24234729e-03],
         [-6.65673462e-04,  6.99589029e-03,  5.13667124e-04,
          -3.09545156e-02,  1.55311367e-02, -1.28526788e-03],
         ...,
         [-5.13409905e-04,  2.94754636e-02,  3.86933039e-04,
          -9.77151766e-02,  5.38862683e-02, -1.43703748e-03],
         [-4.76914225e-04,  2.60920450e-02,  3.96849035e-04,
          -8.79024044e-02,  4.82590161e-02, -1.48609129e-03],
         [-4.47509577e-04,  2.44471598e-02,  4.05806786e-04,
          -8.31923112e-02,  4.55613434e-02, -1.53034646e-03]],

        [[-1.27922176e-04,  9.17735160e-04,  5.96601749e-04,
          -2.23553827e-04,  5.09061059e-03,  3.14573554e-04],
         [-1.29995664e-04,  9.30272508e-04, -2.21381919e-03,
          -2.38052147e-04,  1.30394697e-02,  4.32399707e-03],
         [-1.42584919e-04,  9.26584762e-04, -6.92190649e-03,
          -2.66570045e-04,  2.63817068e-02,  1.10604549e-02],
         ...,
         [-1.05224506e-04,  9.23402957e-04, -3.14861909e-02,
          -2.52005324e-04,  9.58205685e-02,  4.58234847e-02],
         [-5.07956211e-05,  8.77124432e-04, -3.10702045e-02,
          -2.29104029e-04,  9.46226344e-02,  4.52273786e-02],
         [ 8.99509178e-06,  8.28552002e-04, -3.17044780e-02,
          -2.04645301e-04,  9.63912681e-02,  4.61182073e-02]],

        ...,

        [[ 3.06790527e-02, -4.69229592e-04, -1.40120415e-02,
          -5.62681444e-02,  3.56148072e-02,  4.41594794e-02],
         [ 2.86166947e-02, -4.69433493e-04, -1.28445048e-02,
          -5.30526415e-02,  3.33283022e-02,  4.14871387e-02],
         [ 2.69671548e-02, -4.53675282e-04, -1.19169233e-02,
          -5.05187064e-02,  3.15173045e-02,  3.94080095e-02],
         ...,
         [ 1.13557903e-02, -4.95711633e-04, -3.16705951e-03,
          -2.61358209e-02,  1.42979696e-02,  1.90160926e-02],
         [ 1.27154076e-02, -4.99825575e-04, -3.93411005e-03,
          -2.82354727e-02,  1.58148631e-02,  2.07540765e-02],
         [ 1.25487372e-02, -4.98186098e-04, -3.85303050e-03,
          -2.79795900e-02,  1.56622697e-02,  2.05388237e-02]],

        [[-8.75751674e-02,  5.15234133e-04,  3.99009325e-02,
           1.64043508e-04,  8.67289752e-02,  1.64588261e-02],
         [-8.59927535e-02,  5.07136807e-04,  3.90671305e-02,
           1.57669172e-04,  8.51687044e-02,  1.60562098e-02],
         [-8.40341076e-02,  4.97310306e-04,  3.80364209e-02,
           1.46165301e-04,  8.32375810e-02,  1.55601734e-02],
         ...,
         [-4.42830846e-02,  5.44745184e-04,  1.70464683e-02,
           1.88700389e-04,  4.40370329e-02,  5.15085598e-03],
         [-4.69980501e-02,  5.57898660e-04,  1.84792131e-02,
           1.90531457e-04,  4.67159189e-02,  5.85190207e-03],
         [-4.54892330e-02,  5.84791356e-04,  1.76687576e-02,
           2.15217151e-04,  4.52267379e-02,  5.42609999e-03]],

        [[-1.11968769e-02,  4.74887725e-04, -4.49009705e-04,
           1.20749384e-01,  6.05667825e-04, -6.07411638e-02],
         [-1.11482413e-02,  4.79360489e-04, -4.39206400e-04,
           1.20367169e-01,  6.05672423e-04, -6.05327561e-02],
         [-1.10561196e-02,  4.87151759e-04, -4.28938714e-04,
           1.19670786e-01,  6.03428634e-04, -6.01505898e-02],
         ...,
         [-3.65508697e-03,  5.19738067e-04, -4.03439597e-04,
           6.87454566e-02,  5.96358499e-04, -3.23013552e-02],
         [-4.02658712e-03,  5.02632582e-04, -4.23403428e-04,
           7.14262351e-02,  6.01860753e-04, -3.37718427e-02],
         [-3.45655554e-03,  4.88601334e-04, -4.57680319e-04,
           6.76999465e-02,  6.05031382e-04, -3.17338668e-02]]],


       [[[-2.13223975e-02,  1.73388980e-03, -1.92679595e-02,
           7.96076208e-02, -2.01046219e-04, -2.20773537e-02],
         [-2.12766007e-02,  1.73209433e-03, -1.92298945e-02,
           7.94342533e-02, -2.02859199e-04, -2.20294725e-02],
         [-2.11141780e-02,  1.71749317e-03, -1.90936346e-02,
           7.88091123e-02, -2.04164535e-04, -2.18593106e-02],
         ...,
         [-2.12482139e-02,  1.71927875e-03, -1.92035362e-02,
           7.93004334e-02, -1.96612760e-04, -2.19983459e-02],
         [-2.14273781e-02,  1.73368829e-03, -1.93532109e-02,
           7.99819455e-02, -1.93881002e-04, -2.21859459e-02],
         [-2.16050223e-02,  1.74765009e-03, -1.95016135e-02,
           8.06571990e-02, -1.90916544e-04, -2.23717336e-02]],

        [[ 1.57238115e-04, -2.00324133e-01, -5.78788593e-02,
          -7.13430811e-04,  9.55269784e-02,  4.80967946e-02],
         [ 1.56818409e-04, -2.00349376e-01, -5.78858145e-02,
          -7.15270347e-04,  9.55368429e-02,  4.81004603e-02],
         [ 1.56388051e-04, -1.99462324e-01, -5.76194897e-02,
          -7.15111906e-04,  9.51113403e-02,  4.78776209e-02],
         ...,
         [ 1.52210298e-04, -2.01272905e-01, -5.81571087e-02,
          -6.99127617e-04,  9.59847569e-02,  4.83472012e-02],
         [ 1.49269108e-04, -2.03316778e-01, -5.87660298e-02,
          -6.93891896e-04,  9.69638228e-02,  4.88638319e-02],
         [ 1.46415463e-04, -2.05399349e-01, -5.93865067e-02,
          -6.88938599e-04,  9.79606435e-02,  4.93900888e-02]],

        [[-5.36992622e-04, -4.51787091e-05, -1.59301832e-01,
           1.06617194e-02, -4.10196371e-02,  8.41052160e-02],
         [-5.36672713e-04, -4.53461871e-05, -1.59612894e-01,
           1.06717609e-02, -4.11034413e-02,  8.42669755e-02],
         [-5.36608277e-04, -4.56486050e-05, -1.59397781e-01,
           1.06652118e-02, -4.10442203e-02,  8.41558650e-02],
         ...,
         [-5.39096072e-04, -5.13022787e-05, -1.61863059e-01,
           1.07445773e-02, -4.17281538e-02,  8.54670629e-02],
         [-5.40129025e-04, -5.32184058e-05, -1.63734734e-01,
           1.08039444e-02, -4.22437154e-02,  8.64512026e-02],
         [-5.41092770e-04, -5.48095122e-05, -1.65675461e-01,
           1.08653521e-02, -4.27776650e-02,  8.74695331e-02]],

        ...,

        [[ 5.34941256e-02,  3.20886873e-04, -2.51457968e-04,
           3.06647307e-05,  2.15162858e-02, -9.54320952e-02],
         [ 5.28112389e-02,  3.19649669e-04, -2.51953083e-04,
           3.28080314e-05,  2.11611539e-02, -9.42007899e-02],
         [ 5.20445444e-02,  3.18110804e-04, -2.52767903e-04,
           3.55015509e-05,  2.07627174e-02, -9.28183123e-02],
         ...,
         [ 5.62037565e-02,  3.17360653e-04, -2.29602330e-04,
           2.95951995e-05,  2.29159780e-02, -1.00320533e-01],
         [ 5.54710962e-02,  3.20798892e-04, -2.41318310e-04,
           3.03671695e-05,  2.25419998e-02, -9.90006104e-02],
         [ 5.45888022e-02,  3.22568434e-04, -2.48568482e-04,
           2.93601024e-05,  2.20857039e-02, -9.74092484e-02]],

        [[ 1.06543906e-01,  9.51624289e-02,  1.25587821e-01,
           6.12733029e-02,  1.61513716e-01, -5.12324550e-05],
         [ 1.05278440e-01,  9.40392539e-02,  1.24076776e-01,
           6.05625100e-02,  1.59506202e-01, -5.05098906e-05],
         [ 1.03864335e-01,  9.27850008e-02,  1.22388318e-01,
           5.97688630e-02,  1.57261044e-01, -4.85495475e-05],
         ...,
         [ 1.09424755e-01,  9.77332890e-02,  1.29059151e-01,
           6.28846139e-02,  1.66104853e-01, -6.76109994e-05],
         [ 1.10225379e-01,  9.84457508e-02,  1.30021974e-01,
           6.33356795e-02,  1.67392671e-01, -7.88732068e-05],
         [ 1.09823458e-01,  9.80845466e-02,  1.29535139e-01,
           6.31106496e-02,  1.66756436e-01, -7.88595280e-05]],

        [[ 2.68501637e-04,  1.25738000e-03, -1.83554161e-02,
          -2.07910227e-04,  2.54814386e-01,  1.07163712e-02],
         [ 2.67950672e-04,  1.12699484e-03, -1.81090254e-02,
          -2.07986552e-04,  2.51798213e-01,  1.05289817e-02],
         [ 2.66329036e-04,  9.84642189e-04, -1.78388320e-02,
          -2.07312201e-04,  2.48506024e-01,  1.03245908e-02],
         ...,
         [ 1.66765982e-04,  2.43014638e-05, -1.59978364e-02,
          -7.51469925e-05,  2.26094514e-01,  8.85259360e-03],
         [ 1.91836822e-04,  4.65139776e-04, -1.68336295e-02,
          -1.03959173e-04,  2.36371219e-01,  9.51311179e-03],
         [ 2.39659188e-04,  7.56360299e-04, -1.74010713e-02,
          -1.57947550e-04,  2.43222848e-01,  9.97118466e-03]]],


       ...,


       [[[-7.03589874e-04,  4.90555502e-02, -2.67486739e-05,
           8.40369985e-02,  4.88989230e-04,  3.55651714e-02],
         [-7.40665535e-04,  5.64444512e-02, -1.06235639e-04,
           9.84156951e-02,  5.01054281e-04,  4.09632958e-02],
         [-7.55470130e-04,  5.85939474e-02, -1.71460197e-04,
           1.02686554e-01,  4.88851219e-04,  4.25922349e-02],
         ...,
         [-1.44194928e-03,  1.04347326e-01, -6.40013954e-04,
           1.91732660e-01,  1.37195864e-03,  7.58173317e-02],
         [-1.44173636e-03,  1.04337864e-01, -6.39580714e-04,
           1.91713288e-01,  1.37192337e-03,  7.58099779e-02],
         [-1.44143240e-03,  1.04328163e-01, -6.39400969e-04,
           1.91694602e-01,  1.37147785e-03,  7.58029670e-02]],

        [[-6.19392283e-02, -8.02829280e-04, -7.22828358e-02,
           8.97179767e-02,  2.93158889e-02, -4.06674780e-02],
         [-7.21114278e-02, -7.80605653e-04, -8.43143836e-02,
           1.05597161e-01,  3.40913683e-02, -4.69153337e-02],
         [-7.80918002e-02, -7.61836651e-04, -9.13226977e-02,
           1.14943184e-01,  3.69160436e-02, -5.05727082e-02],
         ...,
         [-1.47750393e-01, -3.64279549e-04, -1.73912421e-01,
           2.23536372e-01,  7.01156557e-02, -9.34259966e-02],
         [-1.47737250e-01, -3.64591979e-04, -1.73897296e-01,
           2.23516017e-01,  7.01090395e-02, -9.34180394e-02],
         [-1.47729337e-01, -3.64703272e-04, -1.73887819e-01,
           2.23503754e-01,  7.01050833e-02, -9.34131816e-02]],

        [[ 7.51246512e-02, -3.43024905e-04, -3.06129950e-04,
           1.00888610e-01,  3.11781099e-04,  1.19949924e-03],
         [ 8.46329853e-02, -3.36366240e-04, -3.00369313e-04,
           1.14938878e-01,  3.16630438e-04,  1.22582715e-03],
         [ 9.39279869e-02, -3.58667166e-04, -2.90010183e-04,
           1.28683195e-01,  2.72311183e-04,  1.21890509e-03],
         ...,
         [ 2.10843116e-01, -8.24773626e-04,  7.40397838e-04,
           3.02300453e-01,  5.55779669e-04,  1.50870276e-03],
         [ 2.10830420e-01, -8.24289804e-04,  7.39772746e-04,
           3.02280992e-01,  5.55754115e-04,  1.50885247e-03],
         [ 2.10832074e-01, -8.24360817e-04,  7.39677635e-04,
           3.02283704e-01,  5.55538514e-04,  1.50883605e-03]],

        ...,

        [[-1.78913338e-04,  3.32264267e-02, -2.72755837e-03,
           1.93227883e-02,  6.10980554e-04,  4.89228929e-04],
         [-1.82172487e-04,  3.21231820e-02, -2.59036245e-03,
           1.87625978e-02,  6.16276753e-04,  4.97943314e-04],
         [-1.86261255e-04,  3.10352966e-02, -2.45595095e-03,
           1.82088502e-02,  6.20861596e-04,  5.05337783e-04],
         ...,
         [-2.12227329e-04, -1.85042024e-02,  3.28399171e-03,
          -7.18013244e-03,  4.99975227e-04,  4.04610706e-04],
         [-2.10660262e-04, -1.91417020e-02,  3.35509330e-03,
          -7.50744110e-03,  4.95781016e-04,  3.99913872e-04],
         [-2.08195954e-04, -1.96108744e-02,  3.40529694e-03,
          -7.74747552e-03,  4.90326434e-04,  3.93725233e-04]],

        [[-2.85146106e-02, -6.47557452e-02, -1.48008555e-01,
           3.83670005e-04,  6.87168464e-02, -5.34037352e-02],
         [-2.71136407e-02, -6.18464276e-02, -1.41641036e-01,
           3.85363499e-04,  6.55582547e-02, -5.09118140e-02],
         [-2.57110540e-02, -5.89447655e-02, -1.35283321e-01,
           3.85513878e-04,  6.24021627e-02, -4.84193452e-02],
         ...,
         [ 1.98803693e-02,  3.47205289e-02,  7.03122839e-02,
           3.33244068e-04, -3.97633687e-02,  3.23955938e-02],
         [ 2.02108603e-02,  3.53915244e-02,  7.17891678e-02,
           3.32745316e-04, -4.04987112e-02,  3.29789892e-02],
         [ 2.04863399e-02,  3.59535664e-02,  7.30252489e-02,
           3.32190015e-04, -4.11147214e-02,  3.34700420e-02]],

        [[ 1.34152491e-02,  3.08436714e-02, -1.83534771e-01,
          -1.26511201e-01,  1.60131764e-04, -1.64851299e-04],
         [ 1.28590129e-02,  2.91863550e-02, -1.75061122e-01,
          -1.20537795e-01,  1.61102900e-04, -1.67743288e-04],
         [ 1.22893294e-02,  2.74932943e-02, -1.66411996e-01,
          -1.14434339e-01,  1.61876640e-04, -1.68341532e-04],
         ...,
         [-4.58376808e-03, -2.26962660e-02,  9.06197131e-02,
           6.68439344e-02,  1.62868877e-04, -8.81694796e-05],
         [-4.60721133e-03, -2.27701776e-02,  9.10189077e-02,
           6.71168640e-02,  1.63114033e-04, -8.53607198e-05],
         [-4.65686806e-03, -2.29172558e-02,  9.17732194e-02,
           6.76496848e-02,  1.62832453e-04, -8.49288408e-05]]],


       [[[-1.04113063e-02,  3.71333357e-04,  3.29061040e-05,
          -1.42067205e-04,  1.25012454e-02,  1.24180196e-02],
         [-5.62996836e-03,  3.62607592e-04,  2.57298470e-05,
          -1.50411535e-04,  5.44272875e-03,  9.92425159e-03],
         [-5.05742524e-03,  3.64245672e-04, -4.94875439e-06,
          -1.82708740e-04,  4.65662312e-03,  9.61745251e-03],
         ...,
         [-1.37006612e-02,  3.65308311e-04,  2.62318099e-05,
          -1.69129009e-04,  1.74066387e-02,  1.41381333e-02],
         [-1.14977183e-02,  3.56807868e-04,  2.74528720e-05,
          -1.76302143e-04,  1.41519373e-02,  1.29887126e-02],
         [-8.22967477e-03,  3.40725936e-04,  2.63752372e-05,
          -1.95754998e-04,  9.33521427e-03,  1.12838419e-02]],

        [[ 9.48792044e-03, -9.37483087e-03,  2.76890420e-03,
           9.91578493e-03, -9.83668491e-03,  9.64543317e-03],
         [ 1.44163903e-03, -5.98491356e-03,  2.70234887e-03,
           5.72138978e-03, -4.54861391e-03,  3.40301241e-03],
         [ 1.37226924e-03, -5.92016894e-03,  2.70165340e-03,
           5.48331998e-03, -4.37298696e-03,  3.18206800e-03],
         ...,
         [ 1.40716229e-02, -1.12883346e-02,  2.80554057e-03,
           1.21321082e-02, -1.27439005e-02,  1.30646927e-02],
         [ 1.22684445e-02, -1.05341962e-02,  2.78527150e-03,
           1.11814979e-02, -1.15546305e-02,  1.16564222e-02],
         [ 1.00083370e-02, -9.58780851e-03,  2.76147132e-03,
           1.00236293e-02, -1.00833522e-02,  9.91879310e-03]],

        [[ 4.66369354e-04, -5.69128257e-04, -9.02765244e-03,
           1.10116228e-03, -9.92969144e-03,  8.96762405e-03],
         [ 4.86761099e-04, -5.37254091e-04, -7.14671100e-03,
           1.16711215e-03, -7.63513008e-03,  7.28488946e-03],
         [ 5.14677784e-04, -4.96790919e-04, -7.43771531e-03,
           1.25730317e-03, -8.18939973e-03,  7.69813173e-03],
         ...,
         [ 4.76428511e-04, -5.71397657e-04, -8.23733490e-03,
           1.09263719e-03, -8.89257062e-03,  8.19851365e-03],
         [ 4.84964170e-04, -5.52369049e-04, -8.36231746e-03,
           1.13452901e-03, -9.13171750e-03,  8.38105753e-03],
         [ 4.81861789e-04, -5.48707030e-04, -8.74264166e-03,
           1.14252954e-03, -9.63820331e-03,  8.75638332e-03]],

        ...,

        [[ 1.34558007e-02,  7.70106330e-04, -2.28504126e-04,
          -4.98477230e-03,  5.61407628e-03,  2.64524599e-03],
         [ 1.27826827e-02,  7.61398056e-04, -2.27197525e-04,
          -4.69837245e-03,  5.31215267e-03,  2.36030761e-03],
         [ 1.93667635e-02,  6.66631851e-04, -2.25322903e-04,
          -7.69014284e-03,  8.50372389e-03,  4.86505404e-03],
         ...,
         [ 5.33479974e-02,  3.43197316e-04, -2.76571867e-04,
          -2.28361357e-02,  2.48253476e-02,  1.79143772e-02],
         [ 4.13140617e-02,  4.80563962e-04, -2.74425489e-04,
          -1.74065139e-02,  1.90342609e-02,  1.32938595e-02],
         [ 2.94902418e-02,  6.09680661e-04, -2.59417633e-04,
          -1.21113472e-02,  1.33429943e-02,  8.76033958e-03]],

        [[-2.77420948e-03, -1.65890343e-03, -3.15492034e-05,
           3.48520203e-04,  8.56954139e-04, -4.83862037e-04],
         [-2.08949437e-03, -2.12527346e-03, -2.36011010e-06,
           3.37338599e-04,  8.70732183e-04, -4.97356639e-04],
         [-3.49058723e-03, -1.21903291e-03,  2.17228062e-05,
           3.22541950e-04,  8.88302107e-04, -5.22294315e-04],
         ...,
         [-2.69801589e-03, -1.75454922e-03, -6.97289506e-05,
           3.82278755e-04,  8.24376999e-04, -3.90008936e-04],
         [-4.38594638e-04, -3.22886952e-03, -4.74383451e-05,
           3.73757037e-04,  8.31834681e-04, -4.09212662e-04],
         [ 1.18117873e-03, -4.27415268e-03, -2.01906787e-05,
           3.55502649e-04,  8.46912910e-04, -4.46515362e-04]],

        [[ 3.29363346e-02,  2.22524926e-02,  1.30263669e-02,
           2.56287828e-02,  2.28652004e-02,  3.83236003e-03],
         [ 2.62572113e-02,  1.72743648e-02,  9.50840488e-03,
           2.01405138e-02,  1.76884066e-02,  1.57896883e-03],
         [ 2.70059407e-02,  1.78686827e-02,  9.85890906e-03,
           2.07657833e-02,  1.82120726e-02,  1.82338478e-03],
         ...,
         [ 1.81292612e-02,  1.12407170e-02,  5.20916423e-03,
           1.34196449e-02,  1.13209346e-02, -1.15991163e-03],
         [ 1.39467428e-02,  8.13278370e-03,  3.00600007e-03,
           9.97966342e-03,  8.07191804e-03, -2.56127096e-03],
         [ 1.08794225e-02,  5.85655542e-03,  1.38457050e-03,
           7.45190028e-03,  5.68108633e-03, -3.59171559e-03]]],


       [[[-1.20462491e-05, -3.40775499e-04, -1.40096322e-01,
          -1.25882015e-01,  1.83368713e-01,  8.23178664e-02],
         [-6.53599182e-06, -3.41860199e-04, -1.45275861e-01,
          -1.30611554e-01,  1.90178141e-01,  8.53958130e-02],
         [-3.59121782e-06, -3.44075175e-04, -1.49856657e-01,
          -1.34798497e-01,  1.96180284e-01,  8.81100595e-02],
         ...,
         [-2.30434634e-05, -3.47909110e-04, -1.39948562e-01,
          -1.25762135e-01,  1.83079004e-01,  8.21969062e-02],
         [-2.71132139e-05, -3.48073023e-04, -1.39987543e-01,
          -1.25800252e-01,  1.83107495e-01,  8.22094828e-02],
         [-3.63844483e-05, -3.49714333e-04, -1.38890654e-01,
          -1.24806412e-01,  1.81612521e-01,  8.15350488e-02]],

        [[-1.50170224e-03, -2.32159197e-02, -1.09533668e-01,
          -1.57912388e-01,  2.20339194e-01,  1.92159072e-01],
         [-1.51516614e-03, -2.40114089e-02, -1.13482222e-01,
          -1.63642630e-01,  2.28527486e-01,  1.99244440e-01],
         [-1.51698280e-03, -2.47877762e-02, -1.17323071e-01,
          -1.69230089e-01,  2.36503899e-01,  2.06154078e-01],
         ...,
         [-1.46850443e-03, -2.31926292e-02, -1.09382086e-01,
          -1.57736734e-01,  2.20067978e-01,  1.91947043e-01],
         [-1.46033219e-03, -2.31745988e-02, -1.09280139e-01,
          -1.57602534e-01,  2.19872072e-01,  1.91782296e-01],
         [-1.43732317e-03, -2.29695961e-02, -1.08234294e-01,
          -1.56112984e-01,  2.17730969e-01,  1.89944029e-01]],

        [[-7.45095487e-04,  4.98204958e-03, -2.32430771e-02,
           1.53325677e-01,  1.06479242e-01,  2.00189199e-04],
         [-7.62531301e-04,  5.03047835e-03, -2.39757020e-02,
           1.58419266e-01,  1.10006437e-01,  1.81471012e-04],
         [-7.71799125e-04,  5.07546728e-03, -2.47562304e-02,
           1.63844526e-01,  1.13761380e-01,  1.70308776e-04],
         ...,
         [-7.22673605e-04,  4.96717822e-03, -2.32899673e-02,
           1.53662309e-01,  1.06710069e-01,  2.19617534e-04],
         [-7.14427559e-04,  4.95811645e-03, -2.32512597e-02,
           1.53389022e-01,  1.06518239e-01,  2.25912518e-04],
         [-6.94588001e-04,  4.92871227e-03, -2.29960866e-02,
           1.51620761e-01,  1.05290964e-01,  2.42637761e-04]],

        ...,

        [[-3.22365697e-04, -9.20642018e-02, -4.90762033e-02,
           1.79838225e-01, -5.64232643e-04, -7.52056986e-02],
         [-3.23944900e-04, -9.23490673e-02, -4.92356010e-02,
           1.80360869e-01, -5.58957632e-04, -7.54413158e-02],
         [-3.23762069e-04, -9.23190713e-02, -4.92192283e-02,
           1.80303454e-01, -5.54070983e-04, -7.54170120e-02],
         ...,
         [-7.23131234e-05,  4.06848639e-02,  2.56756265e-02,
          -6.71554878e-02, -4.69206163e-04,  3.57248820e-02],
         [-7.74724103e-05,  1.78808849e-02,  1.27083687e-02,
          -2.42628437e-02, -5.65420080e-04,  1.64458659e-02],
         [-1.35824434e-04, -1.08859856e-02, -3.52500728e-03,
           2.94147637e-02, -6.46688743e-04, -7.64062582e-03]],

        [[-1.25245878e-03,  2.48631288e-04, -5.51154604e-04,
           9.38909245e-04,  2.06267923e-01, -3.08253249e-04],
         [-1.25523657e-03,  2.45840260e-04, -5.48892538e-04,
           9.36647994e-04,  2.07052469e-01, -3.06168658e-04],
         [-1.25704496e-03,  2.44443421e-04, -5.46006195e-04,
           9.35893389e-04,  2.07423121e-01, -3.04393965e-04],
         ...,
         [-9.81202582e-04,  5.91697579e-04, -4.91692044e-04,
           1.59666070e-03, -1.00304045e-01, -7.08538631e-04],
         [-9.70719731e-04,  6.38693455e-04, -5.02919371e-04,
           1.57119764e-03, -6.39193431e-02, -7.11492379e-04],
         [-9.91516165e-04,  6.36087323e-04, -5.26612566e-04,
           1.49507658e-03, -1.15735941e-02, -6.93839334e-04]],

        [[-1.71972781e-01,  6.53291028e-03,  3.39560997e-04,
           2.81810593e-02,  2.60925211e-04,  7.11869821e-02],
         [-1.72744006e-01,  6.55625109e-03,  3.43360472e-04,
           2.83289272e-02,  2.63155787e-04,  7.15182275e-02],
         [-1.73399255e-01,  6.57510757e-03,  3.45649460e-04,
           2.84554958e-02,  2.64483504e-04,  7.18005151e-02],
         ...,
         [ 1.04889952e-01, -1.61083939e-03,  2.69857788e-04,
          -2.61005238e-02,  4.11815941e-04, -4.87454832e-02],
         [ 8.43910053e-02, -1.01326604e-03,  1.90660998e-04,
          -2.20011603e-02,  3.28293972e-04, -3.98008786e-02],
         [ 5.05167991e-02, -2.08284418e-05,  1.16380041e-04,
          -1.52788591e-02,  2.32437858e-04, -2.50617340e-02]]]],
      dtype=float32) has invalid type <class 'numpy.ndarray'>, must be a string or Tensor. (Can not convert a ndarray into a Tensor or Operation.)

In [9]:
# create layers
num_of_aug  = 6
l1_encoder  = CNN(3,1,num_of_aug,           act=tf_relu)
l2_encoder  = CNN(1,  num_of_aug,num_of_aug,act=tf_relu)
l3_encoder  = CNN(3,  num_of_aug,num_of_aug,act=tf_relu)
l4_encoder  = CNN(1,  num_of_aug,num_of_aug,act=tf_relu)
l5_encoder  = CNN(3,  num_of_aug,num_of_aug,act=tf_relu)
l6_encoder  = CNN(1,  num_of_aug,num_of_aug,act=tf_sigmoid)

l1_with_image = CNN(3,num_of_aug*2,num_of_aug*2,act=tf_relu)
l2_with_image = CNN(3,num_of_aug*2,num_of_aug*2,act=tf_relu)
l3_with_image = CNN(3,num_of_aug*2,1,act=tf_iden)

def with_image(input_data):
    _,layer1_g = l1_with_image.feedforward(input_data)
    _,layer2_g = l1_with_image.feedforward(layer1_g)
    _,layer3_g = l1_with_image.feedforward(layer2_g)
    return layer3_g

x_encoding = tf.placeholder(tf.float32,(None,96,96,1))
x_reisze   = tf.image.resize_images(x_encoding,(90,90))
x_reisze   = tf.tile(x_reisze,(1,1,1,num_of_aug))

_,layer1_e = l1_encoder.feedforward(x_encoding)
_,layer2_e = l2_encoder.feedforward(layer1_e)
layer2_e = layer2_e + layer1_e
_,layer3_e = l3_encoder.feedforward(layer2_e)
_,layer4_e = l4_encoder.feedforward(layer3_e)
layer4_e = layer4_e + layer3_e
_,layer5_e = l5_encoder.feedforward(layer4_e)
_,layer6_e = l6_encoder.feedforward(layer5_e)
layer6_e = layer6_e + layer5_e

final_latent  = layer6_e
final_latents = tf.transpose(final_latent,(0,2,1,3))
encoded_gt = tf.concat([final_latent  ,x_reisze],3)
encoded_rd = tf.concat([final_latents ,x_reisze],3)

with_image_gt  = tf.reduce_mean(-tf_tanh(-with_image(encoded_gt)))
with_image_rd  = tf.reduce_mean( tf_tanh( with_image(encoded_rd)))
WITH_IMAGE     = (with_image_rd - with_image_gt) 

LOSS = WITH_IMAGE 
auto_train = tf.train.AdamOptimizer(0.0008).minimize(LOSS)

In [10]:
# train classifier
num_epoch = 200

# read the data
train_images,train_labels,test_images,test_labels = read_STL10_data()
train_images = train_images.mean(3,keepdims=True)
train_images = (train_images-train_images.min((0,1,2),keepdims=True))/(train_images.max((0,1,2),keepdims=True)-train_images.min((0,1,2),keepdims=True)+1e-8)
test_images  = test_images.mean(3,keepdims=True)
test_images  = (test_images-test_images.min((0,1,2),keepdims=True))/(test_images.max((0,1,2),keepdims=True)-test_images.min((0,1,2),keepdims=True)+1e-8)

avg_acc_train = 0; avg_acc_test  = 0; train_acc = [];test_acc = []; dividsion = 1
for iter in range(num_epoch):
    
    # train for training images
    for current_batch_index in range(0,len(train_images),batch_size//dividsion):
        current_batch = train_images[current_batch_index:current_batch_index+batch_size//dividsion]
        current_label = train_labels[current_batch_index:current_batch_index+batch_size//dividsion]
        latent_feature = sess.run(final_latent,feed_dict={x_encoding:current_batch}) 
        latent_feature = np.reshape(np.transpose(latent_feature,(0,3,1,2)),(batch_size//dividsion*num_of_aug,90,90))[:,:,:,None]
        latent_feature = (latent_feature-latent_feature.min((0,1,2),keepdims=True))/(latent_feature.max((0,1,2),keepdims=True)-latent_feature.min((0,1,2),keepdims=True)+1e-8)

        latent_labels  = np.asarray([ [x]* num_of_aug for x in current_label]).reshape((batch_size//dividsion*num_of_aug,10))

        sess_results = sess.run([accuracy,class_train,extra_update_ops],feed_dict={x:latent_feature,y:latent_labels})
        sys.stdout.write(' Current Iter : ' + str(iter) + '/'+ str(num_epoch)  + ' batch : ' + str(current_batch_index) + '/'+ str(len(train_images)) + ' acc : ' + str(sess_results[0]) + '\r')
        sys.stdout.flush(); avg_acc_train = avg_acc_train + sess_results[0]

    # test for training images
    for current_batch_index in range(0,len(test_images),batch_size):
        current_batch  = test_images[current_batch_index:current_batch_index+batch_size]
        current_label  = test_labels[current_batch_index:current_batch_index+batch_size]
        latent_feature = sess.run(final_latent,feed_dict={x_encoding:current_batch})[:,:,:,capture_best_index[0]][:,:,:,None]
        latent_feature = (latent_feature-latent_feature.min((0,1,2),keepdims=True))/(latent_feature.max((0,1,2),keepdims=True)-latent_feature.min((0,1,2),keepdims=True)+1e-8)
       
        sess_results = sess.run([accuracy],feed_dict={x:latent_feature,y:current_label,is_training:False})
        sys.stdout.write(' Current Iter : ' + str(iter) + '/'+ str(num_epoch)  + ' batch : ' + str(current_batch_index) + '/'+ str(len(test_images)) + ' acc : ' + str(sess_results[0]) + '\r')
        sys.stdout.flush(); avg_acc_test = avg_acc_test + sess_results[0] 
        
    # ======================== print reset ========================
    if iter%1 == 0 :
        train_images,train_labels = shuffle(train_images,train_labels)
        sys.stdout.write("Current : "+ str(iter) + "\t" +
              " Train Acc : " + str(np.around(avg_acc_train/(len(train_images)/batch_size*dividsion),3)) + "\t" +
              " Test Acc : "  + str(np.around(avg_acc_test/(len(test_images)/batch_size),3)) + "\t\n")
        sys.stdout.flush();
    avg_acc_train = 0 ; avg_acc_test  = 0

(5000, 96, 96, 3) 1.0 0.0
(5000, 10) 1.0 0.0
(8000, 96, 96, 3) 1.0 0.0
(8000, 10) 1.0 0.0


FailedPreconditionError: Attempting to use uninitialized value Variable_18
	 [[node Variable_18/read (defined at <ipython-input-2-18ed72b3c9c7>:14)  = Identity[T=DT_FLOAT, _class=["loc:@Variable_18"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](Variable_18)]]
	 [[{{node add_10/_31}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_40_add_10", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Variable_18/read', defined at:
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Miniconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Miniconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Miniconda3\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\ProgramData\Miniconda3\lib\asyncio\base_events.py", line 1434, in _run_once
    handle._run()
  File "C:\ProgramData\Miniconda3\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\gen.py", line 1233, in inner
    self.run()
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\ProgramData\Miniconda3\lib\site-packages\ipykernel\kernelbase.py", line 370, in dispatch_queue
    yield self.process_one()
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\gen.py", line 346, in wrapper
    runner = Runner(result, future, yielded)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\gen.py", line 1080, in __init__
    self.run()
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\ProgramData\Miniconda3\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Miniconda3\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Miniconda3\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Miniconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Miniconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\ProgramData\Miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "C:\ProgramData\Miniconda3\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\Miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "C:\ProgramData\Miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-59e4eb51ae53>", line 3, in <module>
    l1_encoder  = CNN(3,1,num_of_aug,           act=tf_relu)
  File "<ipython-input-2-18ed72b3c9c7>", line 14, in __init__
    self.w              = tf.Variable(tf.random_normal([k,k,inc,out],stddev=stddev,seed=2,dtype=tf.float32))
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 183, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 146, in _variable_v1_call
    aggregation=aggregation)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 125, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2444, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 187, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 1329, in __init__
    constraint=constraint)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 1491, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 81, in identity
    return gen_array_ops.identity(input, name=name)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3454, in identity
    "Identity", input=input, name=name)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Variable_18
	 [[node Variable_18/read (defined at <ipython-input-2-18ed72b3c9c7>:14)  = Identity[T=DT_FLOAT, _class=["loc:@Variable_18"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](Variable_18)]]
	 [[{{node add_10/_31}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_40_add_10", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [ ]:
# len(test_images)
accuray_test = 0
for current_batch_index in range(len(test_images)):
    current_batch = test_images[current_batch_index:current_batch_index+1]
    current_label = test_labels[current_batch_index:current_batch_index+1]
    latent_feature = sess.run(layer2_e,feed_dict={x_encoding:current_batch})
    latent_feature = np.transpose(latent_feature,(3,1,2,0))
    sess_results = sess.run(final_soft,feed_dict={x:latent_feature,y:current_label,is_training:False})
    m = stats.mode(np.argmax(sess_results,1))
    if m[0] == np.argmax(current_label,1):
        accuray_test = accuray_test + 1
print(accuray_test)
print(accuray_test/len(test_images))

In [ ]:
    if avg_acc_test/(len(test_images)/batch_size) < avg_acc_train/(len(train_images)/batch_size*dividsion):
        print('\n MAX  \t')
        for current_batch_index in range(0,len(train_images),batch_size):
            current_batch = train_images[current_batch_index:current_batch_index+batch_size]
            sess_results  = sess.run([TOTAL_LOSS,auto_train],feed_dict={x_encoding:current_batch})
            sys.stdout.write(' Current Iter : ' + str(iter) + '/'+ str(num_epoch)  + ' batch : ' + str(current_batch_index) + '/'+ str(len(train_images)) + ' loss : ' + str(sess_results[0]) + '\r')
            sys.stdout.flush(); 

In [102]:
def soft_absolute(v):
    return np.sqrt(v**2 + 1e-8)

Y = soft_absolute(Y)

# Normalize feature across all examples
# Divide each feature by its l2-norm
Y = Y / np.sqrt(np.sum(Y**2,axis=0) + epsilon)        

# Normalize feature per example
Y = Y / np.sqrt(np.sum(Y**2,axis=1)[:,np.newaxis] + epsilon )



NameError: name 'Y' is not defined

In [111]:
temp = np.around(np.random.randn(10,5),3)
print(temp)
print('------------------------')
Y = soft_absolute(temp)
print(np.around(Y,3))
print('------------------------')
Y = Y / np.sqrt(np.sum(Y**2,axis=0) + 1e-8)  
print(Y.sum(0))
print(np.around(Y,3))
print('------------------------')
Y = Y / np.sqrt(np.sum(Y**2,axis=1)[:,np.newaxis] + 1e-8 )
print(Y.sum(1))
print(np.around(Y,3))
print('------------------------')


[[ 0.707 -0.802  1.314 -0.43  -1.583]
 [ 0.362  1.208 -0.248  1.641 -0.217]
 [-0.625 -0.398  1.882 -0.293 -0.04 ]
 [ 0.692 -0.075  0.475  0.241 -0.025]
 [ 0.801  0.009 -1.272 -0.66   0.114]
 [ 1.082  0.568 -1.558  0.065  1.26 ]
 [ 0.95   0.497  0.015 -1.53  -0.516]
 [-1.128  1.052 -1.303 -0.536 -1.12 ]
 [-0.307  0.911  0.69   0.825 -0.821]
 [ 1.279  1.854  1.135 -0.307  1.92 ]]
------------------------
[[0.707 0.802 1.314 0.43  1.583]
 [0.362 1.208 0.248 1.641 0.217]
 [0.625 0.398 1.882 0.293 0.04 ]
 [0.692 0.075 0.475 0.241 0.025]
 [0.801 0.009 1.272 0.66  0.114]
 [1.082 0.568 1.558 0.065 1.26 ]
 [0.95  0.497 0.015 1.53  0.516]
 [1.128 1.052 1.303 0.536 1.12 ]
 [0.307 0.911 0.69  0.825 0.821]
 [1.279 1.854 1.135 0.307 1.92 ]]
------------------------
[2.95283115 2.57352014 2.73688621 2.49156571 2.40396004]
[[0.263 0.28  0.364 0.164 0.5  ]
 [0.135 0.422 0.069 0.626 0.068]
 [0.233 0.139 0.521 0.112 0.013]
 [0.258 0.026 0.131 0.092 0.008]
 [0.298 0.003 0.352 0.252 0.036]
 [0.403 0.198 0.