In [5]:
# import lib
import numpy as np 
import tensorflow as tf
import matplotlib.pyplot as plt
import threading
import multiprocessing
from multiprocessing import Process,Manager,Array
import scipy
np.random.seed(78)
tf.set_random_seed(678)

In [9]:
# function
import time
from multiprocessing import Process, Value, Lock

def func(val, lock):
    for i in range(50):
        time.sleep(0.01)
        with lock:
            val.value += 1

v = Value('i', 0)
lock = Lock()
procs = [Process(target=func, args=(v, lock)) for i in range(10)]

for p in procs: p.start()
for p in procs: p.join()

print(v.value)

0


In [22]:
# another example
def f(a): a[0] = -a[0]

# Create the array
N = int(10)
unshared_arr = scipy.rand(N)
a = Array('d', unshared_arr)
print("Originally, the first two elements of arr = %s"%(a[:2]))

# Create, start, and finish the child process
p = Process(target=f, args=(a,))
p.start()
p.join()

# Print out the changed values
print("Now, the first two elements of arr = %s"%a[:2])

b = np.frombuffer(a.get_obj())
b[0] = 10.0
print(a[0])
print(np.frombuffer(a.get_obj()))

Originally, the first two elements of arr = [0.6455136288662301, 0.644672035880631]
Now, the first two elements of arr = [0.6455136288662301, 0.644672035880631]
10.0
[10.          0.64467204  0.19827176  0.12167553  0.0148732   0.86811063
  0.47694396  0.41602761  0.43647547  0.60237762]


In [24]:
# declare
num_epoch    = 2000000
ground_truth = np.random.uniform(0,1,10)
expected     = np.zeros(10)
pull_count   = np.zeros(10) 
print(np.around(ground_truth,2))
print(expected)
print(pull_count)

[0.67 0.61 0.32 0.03 0.44 0.21 0.11 0.9  0.97 0.99]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
# train 
for iter in range(num_epoch):
    current_action             = np.random.randint(10)
    pull_count[current_action] = pull_count  [current_action] + 1
    if np.random.uniform(0,1)  < ground_truth[current_action]: current_reward = 1
    else: current_reward       = 0
    expected[current_action]   = expected[current_action] + (1/pull_count[current_action]) * (current_reward-expected[current_action])

print(np.around(ground_truth,2)); print(np.around(expected,2)); print(pull_count)

[0.67 0.61 0.32 0.03 0.44 0.21 0.11 0.9  0.97 0.99]
[0.67 0.61 0.32 0.03 0.44 0.2  0.11 0.9  0.97 0.99]
[799835. 799836. 800616. 800797. 799769. 799458. 799539. 800827. 800381.
 798942.]
