In [12]:
import numpy as np
import tensorflow as tf
from numpy.linalg import inv,pinv,eigh

In [15]:
#create upper triangular matrix
A_vec = np.array([-3,-2,4,-2,1,1,4,1,5])
A = np.reshape(A_vec,[3,3])
D,U = eigh(A)
D_diag = np.diag(D)
print(D)
print(D_diag)
print(U)

temp = inv(U).T

[-5.43071561  1.76904987  6.66166575]
[[-5.43071561  0.          0.        ]
 [ 0.          1.76904987  0.        ]
 [ 0.          0.          6.66166575]]
[[ 0.87118413 -0.31452619 -0.37697678]
 [ 0.32778267  0.94426587 -0.0303395 ]
 [-0.36550888  0.09713517 -0.92572567]]


In [5]:
#tensorflow variables
A_tf = tf.Variable(tf.constant(A,dtype=tf.float64))
e_tf = tf.self_adjoint_eig(A_tf)
#initialise variables and run session
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(e_tf))

(array([-5.43071561,  1.76904987,  6.66166575]), array([[-0.87118413,  0.31452619, -0.37697678],
       [-0.32778267, -0.94426587, -0.0303395 ],
       [ 0.36550888, -0.09713517, -0.92572567]]))
