In [5]:
from autograd import elementwise_grad as egrad
import autograd.numpy as np
from autograd import grad 
np.random.seed(0)

def my_svd(x): return np.linalg.svd(x,full_matrices=False)
def mean(x):   return x - x.mean(0,keepdims=True)

grad_mean = egrad(mean)
grad_svd  = grad(my_svd)

x = np.random.randn(3,3)
print(x)

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]]


In [6]:
grad_mean(x)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
grad_svd(x)

TypeError: Grad only applies to real scalar-output functions. Try jacobian or elementwise_grad.